replicaCount: 1

image:
  repository: peterouob/golang_full_devops
  pullPolicy: IfNotPresent
  tag: "10072913988"

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific